version: 2.1

jobs:
  test:
    parameters:
      python:
        type: string
      toxenv:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
    steps:
      - checkout
      - run: pip install tox
      - run: tox -e << parameters.toxenv >>

workflows:
  all-tests:
    jobs:
      - test:
          name: "python-3.3"
          python: "3.3"
          toxenv: "py33"
      - test:
          name: "python-3.4"
          python: "3.4"
          toxenv: "py34"
      - test:
          name: "python-3.5"
          python: "3.5"
          toxenv: "py35"
      - test:
          name: "python-3.6"
          python: "3.6"
          toxenv: "py36"
      - test:
          name: "python-3.7"
          python: "3.7"
          toxenv: "py37"
      - test:
          name: "python-3.8"
          python: "3.8"
          toxenv: "py38"
