version: 2

jobs:
  # using tox
  toxify:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run: pyenv global 3.3.7 3.4.10 3.5.9
      - run: pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
